#!/bin/bash
set -e

# create notroot user if needed
if [[ "$(getent passwd notroot)" == "" ]]
then
  useradd --no-create-home notroot
  passwd -d notroot
  passwd -l notroot
fi

if [[ "$1" = "configure" ]]
then
  mkdir -p /etc/icanhazuuid
  chown -R notroot:notroot icanhazuuid

  setcap 'cap_net_bind_service=+ep' /usr/bin/icanhazuuid

  systemctl enable icanhazuuid
  systemctl daemon-reload
fi
